image: Visual Studio 2017 Preview
init:
  - git config --global core.autocrlf true
before_build:
  - appveyor-retry dotnet restore -v Minimal
test: on
test_script:
  - ps: .\run-tests.ps1
deploy: off
